### ISSUE TITLE
[BUG]: cluster-side powerscale.GroupnetResource.Description updates invisible to terraform

### ISSUE THREAD

**Issue by petew-nfx** [dell/dell-terraform-providers#12]
### Bug Description

State for GroupnetResource's "description" is not updated on "terraform refresh" or on "terraform plan", unlike that of SubnetResource and others. This results in cluster-side changes to a groupnet's description being invisible to terraform.

### Resource or DataSource Name

Groupnet

### Terraform Version

Terraform 1.6.6

### OneFS Version

9.4.0.13

### go Version

go 1.21.5

### Unisphere Version

N/A

### Operating System

MacOS Darwin Kernel Version 23.2.0

### Steps to Reproduce

- Create/Import a groupnet, .tf file has description field defined.
- "terraform plan" reports no changes.
- Change groupnet description on cluster
- "terraform plan" reports no changes. "terraform refresh" followed by "terraform state show powerscale_groupnet.<id>" does not reflect the current cluster value of description

### Expected Behavior

"terraform plan" and "terraform refresh" should update state with current value of groupnet description.

### Actual Behavior

"terraform plan" and "terraform refresh" fail to update state with current value of groupnet description.

**Comment by taohe1012** [comment]
hi @petew-nfx , I checked the behavior is workable:
    > Create/Import a groupnet, .tf file has description field defined.
    > update its description in the groupnet, .tf file
    > "terraform plan" reports the description changed 
    > "terraform apply"  groupnet's description is also changed on cluster.
Changing groupnet's description from terraform side is workable. 
And for my understanding, your request is to sync the groupnet description using ''terraform refresh" when the description is changed manually on the cluster side ?

**Comment by petew-nfx** [comment]
After importing a groupnet from the cluster and creating the appropriate .tf file, running "terraform plan" shows no actions.
Thereafter changing the groupnet's description using "isi network groupnets modify" should result in "terraform plan" showing the need to change the description to match that in the .tf file. It does not. 
Additionally running "terraform refresh" should update the description of the groupnet resource in the terraform state. It does not.

As a counter example, changing a network pool's description works as expected.

**Comment by taohe1012** [comment]
hi @petew-nfx , you mean when the description is changed manually on the cluster side, "terraform plan" should report its change and "terraform refresh" should update the description  in the terraform state ?

**Comment by taohe1012** [comment]
hi @petew-nfx , I will summary this issue and add this to our backlog. If there is any further question regarding this issue, I will update you promptly. Thanks.

**Comment by forrestxia** [comment]
Close this since PR 127 with fix has been merged and released.
