### ISSUE TITLE
[BUG]: cluster-side powerscale.AccessZone.AuthProviders updates invisible to terraform

### ISSUE THREAD

**Issue by petew-nfx** [dell/dell-terraform-providers#13]
### Bug Description

State for AccessZoneResource's  "custom_providers" is not updated on "terraform refresh" or on "terraform plan", whereas "auth_providers" is updated. This results in cluster-side changes to a AccessZone "auth_providers" being invisible to terraform as "custom_providers" drives plan/apply.

### Resource or DataSource Name

AccessZone

### Terraform Version

Terraform 1.6.6

### OneFS Version

9.4.0.13

### go Version

go 1.21.5

### Unisphere Version

N/A

### Operating System

MacOS Darwin Kernel Version 23.2.0

### Steps to Reproduce

- Create/Import an AccessZone.
- "terraform plan" reports no changes.
- Change auth providers for Zone on cluster
- "terraform plan" reports no changes. "terraform refresh" followed by "terraform state show powerscale_accesszone.<id>" does not reflect the current cluster value of description in "custom_providers" where is does in "auth_providers"

### Expected Behavior

"terraform plan" and "terraform refresh" should update state with current value of zone "auth_providers" in "custom_providers"

### Actual Behavior

"terraform plan" and "terraform refresh" fail to update state with current value of zone "auth_providers" in "custom_providers"

**Comment by taohe1012** [comment]
hi @petew-nfx , this issue is similar to the issue - https://github.com/dell/dell-terraform-providers/issues/12
we will solve them together in our plan, and welcome for more further comment, thanks.

**Comment by forrestxia** [comment]
Close since PR 127 has been merged and released.
